# Generated by Django 4.2.4 on 2023-08-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_pirce',
            new_name='unit_price',
        ),
    ]
