# Generated by Django 4.2.4 on 2023-08-21 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_unit_pirce_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
